### ISSUE TITLE
Porting to docs.sannybuilder.com

### ISSUE THREAD

**Issue by x87** [MatiDragon-YT/doc-chm#1]
Hi @MatiDragon-YT 

Do you have any plans on migrating this documentation over to docs.sannybuilder.com?

**Comment by MatiDragon-YT** [comment]
Hi @x87 :)

Truth be told, at one point I thought I'd go on to ask if I could include this documentation at docs.sannybuilder.com, but then my PC broke.
Now I was just thinking about uploading it to my site, so I could give it some more maintenance, like to Markdown support via JavaScript and a little update to the syntax highlighter.


 If you want, you can port/migrate it to docs.sannybuilder.com.

**Comment by x87** [comment]
>If you want, you can port/migrate it to docs.sannybuilder.com.

I don't think I can, as I don't know Spanish. I can create a new branch in docs repo (similar to the [ru branch](https://github.com/sannybuilder/docs/tree/ru) with Russian translation) and let you work on that if you will.

**Comment by MatiDragon-YT** [comment]
Mm..
Okay... I think I can do it!
